name: Deploy to Lightsail

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
        
    - name: Check Lightsail instances
      run: |
        echo "Checking Lightsail instances in region ${{ secrets.AWS_REGION }}:"
        aws lightsail get-instances --region ${{ secrets.AWS_REGION }}
        echo ""
        echo "If no instances are shown above, you need to create a Lightsail instance first."
        
    - name: Deploy to Lightsail via SSH
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          echo "Starting deployment..."
          cd discord-platoon-bot
          echo "Pulling latest code..."
          git pull origin main
          echo "Installing dependencies..."
          npm install
          echo "Restarting bot..."
          pm2 restart discord-platoon-bot
          echo "Checking status..."
          pm2 status
          echo "Deployment complete!"
          
    - name: Verify deployment
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.LIGHTSAIL_HOST }}
        username: ${{ secrets.LIGHTSAIL_USERNAME }}
        key: ${{ secrets.LIGHTSAIL_SSH_KEY }}
        script: |
          pm2 status
          pm2 logs discord-platoon-bot --lines 5 